name: Veracode Pipeline SAST Reusable Workflow

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
    secrets:
      VERACODE_API_ID:
        required: true
      VERACODE_API_KEY:
        required: true
        
jobs:
  pipeline-sast:
    name: Veracode Pipeline SAST
    runs-on: ubuntu-latest

    steps:
      # Prepare environment   
      - name: Setup Java JDK
        uses: actions/setup-java@v3.4.1
        with:
          # The Java version to set up. Takes a whole or semver Java version. See examples of supported syntax in README file
          java-version: '11'
          distribution: 'microsoft'

      - name: Verify Java
        run: 'java --version'

      - name: Download the Pipeline Scanner
        uses: wei/curl@master
        with:
          args: -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
      
      - name: Unzip the Pipeline Scanner
        run: unzip pipeline-scan-LATEST.zip
           
      - name: Get Present Directory
        run: pwd
    
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.2
        with:
          # Artifact name
          name: ${{inputs.artifact-name}}
          # Destination path
          path: ${{github.workspace}}
          
      - name: Confirm Contents
        run: ls -la
      
      - name: Run Pipeline Scanner
        run: java -Dpipeline.debug=false -jar pipeline-scan.jar --veracode_api_id "${{secrets.VERACODE_API_ID}}" --veracode_api_key "${{secrets.VERACODE_API_KEY}}" --file app/target/verademo.war -jf veracode-pipeline-results.json --fail_on_severity="Very High, High"

      - name: Upload analysis results
        uses: actions/upload-artifact@v2
        with:
            name: veracode-pipeline-results.json
            path: ${{github.workspace}}/veracode-pipeline-results.json
  
      - name: Veracode Upload And Scan
        # You may pin to the exact commit or the version.
        # uses: veracode/veracode-uploadandscan-action@35794dab9fbcd28fac19e44963f80646b27f4a7f
        uses: veracode/veracode-uploadandscan-action@0.2.4
        with:
            # appname
            appname: ${{inputs.profile-name}}
            # createprofile
            createprofile: true
            # filepath
            filepath: ./application.zip
            # version
            version: ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
            # vid
            vid: ${{secrets.VERACODE_API_ID}}
            # vkey
            vkey: ${{secrets.VERACODE_API_KEY}}
            # true or false
            createsandbox: true
            # name of the sandbox
            sandboxname: 'Release Candidate'
